# This is a basic workflow to help you get started with Actions

name: Check scatter submission

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request event but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Get the names of the files changed in this PR
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
             Scatter/submissions/**

      # If Scatter files have changed, running script to check files
      - name: Check Scatter Working Group submission files
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: python Scatter/tests/check_scatter_submission.py $ALL_CHANGED_FILES
